### ISSUE TITLE
Add API one place request

### ISSUE THREAD

**Issue by Derimarg** [Derimarg/destination-hub#23]
The request is to get data for places in that city, so now we want to add get a specific place, and with this, we are going to be able to when clicking place saved, it will show the card for that place.

**Comment by bgswilde** [comment]
Alternative idea I'm remembering from our taskmaster module work... when we fetch and then display data in a card, my understanding is that the data has been dynamically inserted into the document. So we should be able to save the data from the DOM element into localStorage. At least that's what we did in the taskmaster project. I'll do some looking into that...

**Comment by Derimarg** [comment]
yes, and that part is ready, right now, is saving that data in local storage, but for some reason, the API gives a message that the properties are limited.
